package com.nutech.sehatconnect.entity;

import java.util.Date;

/**
 * HealthResult entity — stored in data/health_results.json.
 *
 * Removed Firestore-specific comments; 'id' is now a plain UUID.
 *
 * OOP concept: Encapsulation — fields private, accessed via getters/setters.
 */
public class HealthResult {

    private String id;              // UUID, auto-generated by UserService
    private String calculatorType;  // e.g. "BMI", "Calorie", "Sleep"
    private double resultValue;
    private String advice;
    private Date timestamp;
    private String userId;          // references User.id

    // Default constructor required by Jackson
    public HealthResult() {
        this.timestamp = new Date();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getCalculatorType() { return calculatorType; }
    public void setCalculatorType(String calculatorType) { this.calculatorType = calculatorType; }

    public double getResultValue() { return resultValue; }
    public void setResultValue(double resultValue) { this.resultValue = resultValue; }

    public String getAdvice() { return advice; }
    public void setAdvice(String advice) { this.advice = advice; }

    public Date getTimestamp() { return timestamp; }
    public void setTimestamp(Date timestamp) { this.timestamp = timestamp; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
}
