package com.nutech.sehatconnect.entity;

import java.util.List;

/**
 * User entity — stored in data/users.json.
 *
 * The 'firebaseUid' field has been removed; 'id' (a UUID) now serves
 * as the unique identifier for each user.
 *
 * OOP concept: Encapsulation — all fields are private, accessed via getters/setters.
 */
public class User {

    private String id;       // UUID, auto-generated by UserService
    private String name;
    private int age;
    private String gender;
    private double weight;
    private double height;
    private List<HealthResult> healthHistory; // not persisted in users.json (kept separate)

    // Default constructor required by Jackson for deserialisation
    public User() {}

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }

    public String getGender() { return gender; }
    public void setGender(String gender) { this.gender = gender; }

    public double getWeight() { return weight; }
    public void setWeight(double weight) { this.weight = weight; }

    public double getHeight() { return height; }
    public void setHeight(double height) { this.height = height; }

    public List<HealthResult> getHealthHistory() { return healthHistory; }
    public void setHealthHistory(List<HealthResult> healthHistory) { this.healthHistory = healthHistory; }
}
